# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activist',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
