# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:03
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170722_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activist',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
